name: Update Daily AITA Posts

on:
  schedule:
    # Runs every day at 05:00 UTC (adjust as needed)
    # Use crontab syntax: minute hour day(month) month day(week)
    # See: https://crontab.guru/
    - cron: '0 5 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  run_scraper:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # Use the latest checkout action

      - name: Set up Python
        uses: actions/setup-python@v5 # Use the latest Python setup action
        with:
          python-version: '3.9' # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw pandas # Add any other dependencies your script needs

      - name: Run AITA scraper script
        env: # Make secrets available as environment variables
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: python generate_daily_posts.py # Execute your script

      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]' # Set committer name
          git config --global user.email 'github-actions[bot]@users.noreply.github.com' # Set committer email
          git add top_aita_posts.json # Stage the generated JSON file
          # Check if there are staged changes
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of AITA posts [skip ci]" # Commit changes
            git push # Push changes back to the repository
          fi