name: Update Daily AITA Posts (with Gemini)

on:
  schedule:
    - cron: '0 5 * * *' # Runs every day at 05:00 UTC
  workflow_dispatch:

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install google-generativeai and praw
          pip install praw google-generativeai

      - name: Run AITA scraper script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          # Add the Google API Key secret
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python generate_daily_posts.py

      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add top_aita_posts.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of AITA posts (Gemini Summary) [skip ci]" # Updated commit message
            git push
          fi